library identifier: 'jenkins-pipeline-demo-library@master', 
        retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/ikekim/jenkins-pipeline-demo-library.git'])

pipeline {
    agent any
    stages {
        stage('Audit tools') {                        
            steps {
                auditTools()
            }
        }
    }
}



Started by user psod
Obtained m3/demo2/2.1/Jenkinsfile from git https://github.com/ikekim/jenkins-pipeline-demos.git
[Pipeline] Start of Pipeline
[Pipeline] library
Loading library jenkins-pipeline-demo-library@master
Attempting to resolve master from remote references...
 > git --version # timeout=10
 > git --version # 'git version 2.24.1'
 > git ls-remote -- https://github.com/ikekim/jenkins-pipeline-demo-library.git # timeout=10
Found match: refs/heads/master revision 06d150cdcf6abec44d315157c6e43dfc9d3ad5fc
The recommended git tool is: NONE
No credentials specified
 > git rev-parse --resolve-git-dir /data/workspace/demo2-1@libs/jenkins-pipeline-demo-library/.git # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/ikekim/jenkins-pipeline-demo-library.git # timeout=10
Fetching without tags
Fetching upstream changes from https://github.com/ikekim/jenkins-pipeline-demo-library.git
 > git --version # timeout=10
 > git --version # 'git version 2.24.1'
 > git fetch --no-tags --force --progress -- https://github.com/ikekim/jenkins-pipeline-demo-library.git +refs/heads/*:refs/remotes/origin/* # timeout=10
Checking out Revision 06d150cdcf6abec44d315157c6e43dfc9d3ad5fc (master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 06d150cdcf6abec44d315157c6e43dfc9d3ad5fc # timeout=10
Commit message: "Fix stage order"
First time build. Skipping changelog.
[Pipeline] node
Running on Jenkins in /data/workspace/demo2-1
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Declarative: Checkout SCM)
[Pipeline] checkout
Selected Git installation does not exist. Using Default
The recommended git tool is: NONE
No credentials specified
 > git rev-parse --resolve-git-dir /data/workspace/demo2-1/.git # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/ikekim/jenkins-pipeline-demos.git # timeout=10
Fetching upstream changes from https://github.com/ikekim/jenkins-pipeline-demos.git
 > git --version # timeout=10
 > git --version # 'git version 2.24.1'
 > git fetch --tags --force --progress -- https://github.com/ikekim/jenkins-pipeline-demos.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
Checking out Revision c0276be6367fe57ef4edb931579fa270902e2f85 (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f c0276be6367fe57ef4edb931579fa270902e2f85 # timeout=10
Commit message: "Update Jenkinsfile"
 > git rev-list --no-walk 481d5591e12d4525133d1ddfb244854dff20fb03 # timeout=10
[Pipeline] }
[Pipeline] // stage
[Pipeline] withEnv
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Audit tools)
[Pipeline] node
Running on Jenkins in /data/workspace/demo2-1@2
[Pipeline] {
[Pipeline] sh
+ git version
git version 2.24.1
+ docker version
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0d8d4f9d2a8e8736e9c993e672b41f3
 Built:             Thu Mar 12 16:14:39 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          20.10.11
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       847da18
  Built:            Thu Nov 18 00:35:39 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
+ dotnet --list-sdks
3.1.201 [/usr/share/dotnet/sdk]
+ dotnet --list-runtimes
Microsoft.AspNetCore.App 3.1.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS